// src/ui/react/VideoPlayer.tsx
import { useEffect, useRef, useImperativeHandle, forwardRef } from 'react';
import * as React from 'react';
import { registerJaaqComponents } from '@ui/webcomponents/register';
import { JaaqVideoPlayerElement } from '@ui/webcomponents/VideoPlayer';
import type { VideoDTO } from '@src/types';
import type { PlayerConfig, PlayerState } from '@ui/shared/types';

if (typeof window !== 'undefined') {
  registerJaaqComponents();
}

type VideoPlayerProps = PlayerConfig & {
  onPlay?: () => void;
  onPause?: () => void;
  onError?: (_error: Error) => void;
  onLoaded?: (_video: VideoDTO) => void;
  onTimeUpdate?: (_time: number) => void;
  onVolumeChange?: (_volume: number) => void;
  onEnded?: () => void;
  onFullscreenChange?: (_isFullscreen: boolean) => void;
  showInfo?: boolean;
};

type VideoPlayerHandle = {
  play: () => void;
  pause: () => void;
  setVolume: (_volume: number) => void;
  toggleMute: () => void;
  seek: (_time: number) => void;
  getState: () => PlayerState | null;
  destroy: () => void;
};

function VideoPlayerComponent(
  {
    videoId,
    apiKey,
    clientId,
    client,
    baseUrl,
    apiVersion,
    autoplay = false,
    controls = true,
    width = '100%',
    height = 'auto',
    className = '',
    showLogo = true,
    showTitle = true,
    showAuthor = true,
    showDescription = true,
    showCaptions = true,
    startMuted = false,
    onPlay,
    onPause,
    onError,
    onLoaded,
    onTimeUpdate,
    onVolumeChange,
    onEnded,
    onFullscreenChange,
    showInfo = false,
  }: VideoPlayerProps,
  ref: React.ForwardedRef<VideoPlayerHandle>,
): React.ReactElement {
  const playerRef = useRef<JaaqVideoPlayerElement>(null);
  const videoDataRef = useRef<VideoDTO | null>(null);

  useImperativeHandle(ref, () => ({
    play: () => playerRef.current?.play(),
    pause: () => playerRef.current?.pause(),
    setVolume: (volume: number) => playerRef.current?.setVolume(volume),
    toggleMute: () => playerRef.current?.toggleMute(),
    seek: (time: number) => playerRef.current?.seek(time),
    getState: () => playerRef.current?.getState() || null,
    destroy: () => playerRef.current?.destroy(),
  }));

  const handleLoaded = (e: Event) => {
    const detail = (e as CustomEvent).detail;
    videoDataRef.current = detail;
    onLoaded?.(detail);
  };

  const handlePlay = () => onPlay?.();
  const handlePause = () => onPause?.();
  const handleTimeUpdate = (e: Event) => {
    const time = (e as CustomEvent).detail;
    onTimeUpdate?.(time);
  };
  const handleVolumeChange = (e: Event) => {
    const volume = (e as CustomEvent).detail;
    onVolumeChange?.(volume);
  };
  const handleEnded = () => onEnded?.();
  const handleError = (e: Event) => {
    const error = (e as CustomEvent).detail;
    onError?.(error);
  };
  const handleFullscreenChange = (e: Event) => {
    const isFullscreen = (e as CustomEvent).detail;
    onFullscreenChange?.(isFullscreen);
  };

  useEffect(() => {
    const player = playerRef.current;
    if (!player) return;

    if (client) {
      player.client = client;
    }

    player.addEventListener('jaaq:loaded', handleLoaded);
    player.addEventListener('jaaq:play', handlePlay);
    player.addEventListener('jaaq:pause', handlePause);
    player.addEventListener('jaaq:timeupdate', handleTimeUpdate);
    player.addEventListener('jaaq:volumechange', handleVolumeChange);
    player.addEventListener('jaaq:ended', handleEnded);
    player.addEventListener('jaaq:error', handleError);
    player.addEventListener('jaaq:fullscreenchange', handleFullscreenChange);

    return () => {
      player.removeEventListener('jaaq:loaded', handleLoaded);
      player.removeEventListener('jaaq:play', handlePlay);
      player.removeEventListener('jaaq:pause', handlePause);
      player.removeEventListener('jaaq:timeupdate', handleTimeUpdate);
      player.removeEventListener('jaaq:volumechange', handleVolumeChange);
      player.removeEventListener('jaaq:ended', handleEnded);
      player.removeEventListener('jaaq:error', handleError);
      player.removeEventListener('jaaq:fullscreenchange', handleFullscreenChange);
    };
  }, [client, onPlay, onPause, onError, onLoaded, onTimeUpdate, onVolumeChange, onEnded, onFullscreenChange]);

  useEffect(() => {
    const player = playerRef.current;
    if (!player) return;
    player.setAttribute('start-muted', startMuted ? 'true' : 'false');
  }, [startMuted]);

  return (
    <div style={{ width, height }} className={className}>
      <jaaq-video-player
        ref={playerRef}
        video-id={videoId}
        api-key={apiKey}
        client-id={clientId}
        base-url={baseUrl}
        api-version={apiVersion}
        autoplay={autoplay ? 'true' : 'false'}
        controls={controls ? 'true' : 'false'}
        show-logo={showLogo ? 'true' : 'false'}
        show-title={showTitle ? 'true' : 'false'}
        show-author={showAuthor ? 'true' : 'false'}
        show-description={showDescription ? 'true' : 'false'}
        show-captions={showCaptions ? 'true' : 'false'}
        start-muted={startMuted ? 'true' : 'false'}
        width="100%"
        height="auto"
      />
      {showInfo && videoDataRef.current && (
        <div className="jaaq-video-info" style={{ marginTop: '16px', padding: '16px', background: '#f8f9fa', borderRadius: '8px' }}>
          <h3 style={{ margin: '0 0 12px 0', fontSize: '18px' }}>
            {videoDataRef.current.question || videoDataRef.current.description || 'Untitled Video'}
          </h3>
          <p style={{ margin: '0 0 8px 0' }}>
            <strong>Video ID:</strong> {videoDataRef.current.id}
          </p>
          <p style={{ margin: '0 0 8px 0' }}>
            <strong>Duration:</strong> {videoDataRef.current.duration || 'Unknown'} seconds
          </p>
        </div>
      )}
    </div>
  );
}

VideoPlayerComponent.displayName = 'VideoPlayer';

export const VideoPlayer = forwardRef<VideoPlayerHandle, VideoPlayerProps>(VideoPlayerComponent);

// src/ui/webcomponents/VideoPlayer.ts
import { JaaqVideoPlayer } from '@ui/vanilla/VideoPlayer';
import type { JaaqClient } from '@src/index';
import type { PlayerState } from '@ui/shared/types';
import sharedStyles from '@ui/shared/styles.css';
import vanillaStyles from '@ui/vanilla/styles.css';

const COMPONENT_STYLES = `
:host {
  display: block;
  width: 100%;
}

:host([hidden]) {
  display: none;
}
`;

/**
 * Custom web component for JAAQ video player with Shadow DOM encapsulation
 * Provides a framework-agnostic video player with custom controls and HLS support
 *
 * @example
 * // Declarative usage
 * <jaaq-video-player
 *   video-id="video-123"
 *   api-key="key"
 *   client-id="client"
 *   autoplay="false">
 * </jaaq-video-player>
 *
 * @example
 * // Programmatic usage
 * const player = document.createElement('jaaq-video-player');
 * player.setAttribute('video-id', 'video-123');
 * player.addEventListener('jaaq:play', () => console.log('Playing'));
 * document.body.appendChild(player);
 */
export class JaaqVideoPlayerElement extends HTMLElement {
  private player: JaaqVideoPlayer | null = null;
  private container: HTMLDivElement | null = null;
  private clientInstance: JaaqClient | null = null;
  private connected = false;

  static get observedAttributes() {
    return [
      'video-id',
      'api-key',
      'client-id',
      'autoplay',
      'base-url',
      'width',
      'height',
      'controls',
      'show-logo',
      'show-title',
      'show-author',
      'show-description',
      'show-captions',
      'start-muted',
    ];
  }

  constructor() {
    super();
    this.attachShadow({ mode: 'open' });
  }

  connectedCallback() {
    this.connected = true;
    this.render();
    this.initPlayer();
  }

  disconnectedCallback() {
    this.connected = false;
    this.destroyPlayer();
  }

  attributeChangedCallback(name: string, oldValue: string | null, newValue: string | null) {
    if (!this.connected || oldValue === newValue) return;

    if (name === 'video-id' && this.player) {
      this.destroyPlayer();
      this.initPlayer();
    } else if (name === 'width' || name === 'height') {
      this.updateContainerStyles();
    } else if (
      name === 'controls' ||
      name === 'show-logo' ||
      name === 'show-title' ||
      name === 'show-author' ||
      name === 'show-description' ||
      name === 'show-captions' ||
      name === 'start-muted'
    ) {
      if (this.player) {
        const features: any = {};
        if (name === 'controls') {
          features.controls = !this.hasAttribute('controls') || this.getAttribute('controls') !== 'false';
        } else if (name === 'show-logo') {
          features.showLogo = !this.hasAttribute('show-logo') || this.getAttribute('show-logo') !== 'false';
        } else if (name === 'show-title') {
          features.showTitle = !this.hasAttribute('show-title') || this.getAttribute('show-title') !== 'false';
        } else if (name === 'show-author') {
          features.showAuthor = !this.hasAttribute('show-author') || this.getAttribute('show-author') !== 'false';
        } else if (name === 'show-description') {
          features.showDescription = !this.hasAttribute('show-description') || this.getAttribute('show-description') !== 'false';
        } else if (name === 'show-captions') {
          features.showCaptions = !this.hasAttribute('show-captions') || this.getAttribute('show-captions') !== 'false';
        } else if (name === 'start-muted') {
          features.startMuted = this.hasAttribute('start-muted') && this.getAttribute('start-muted') !== 'false';
        }
        this.player.setFeatures(features);
      }
    }
  }

  private render() {
    if (!this.shadowRoot) return;

    const styleSheet = document.createElement('style');
    styleSheet.textContent = `
      ${sharedStyles}
      ${vanillaStyles}
      ${COMPONENT_STYLES}
    `;

    this.container = document.createElement('div');
    this.container.className = 'jaaq-webcomponent-container';

    this.shadowRoot.appendChild(styleSheet);
    this.shadowRoot.appendChild(this.container);

    this.updateContainerStyles();
  }

  private updateContainerStyles() {
    if (!this.container) return;

    const width = this.getAttribute('width') || '100%';
    const height = this.getAttribute('height') || 'auto';

    this.container.style.width = width;
    this.container.style.height = height;
  }

  private async initPlayer() {
    if (!this.container || this.player) return;

    const videoId = this.getAttribute('video-id');
    if (!videoId) {
      this.emitError(new Error('video-id attribute is required'));
      return;
    }

    const apiKey = this.getAttribute('api-key');
    const clientId = this.getAttribute('client-id');
    const baseUrl = this.getAttribute('base-url') || undefined;
    const apiVersion = this.getAttribute('api-version') || undefined;
    const autoplay = this.hasAttribute('autoplay') && this.getAttribute('autoplay') !== 'false';
    const controls = !this.hasAttribute('controls') || this.getAttribute('controls') !== 'false';

    const showLogo = !this.hasAttribute('show-logo') || this.getAttribute('show-logo') !== 'false';
    const showTitle = !this.hasAttribute('show-title') || this.getAttribute('show-title') !== 'false';
    const showAuthor = !this.hasAttribute('show-author') || this.getAttribute('show-author') !== 'false';
    const showDescription = !this.hasAttribute('show-description') || this.getAttribute('show-description') !== 'false';
    const showCaptions = !this.hasAttribute('show-captions') || this.getAttribute('show-captions') !== 'false';
    const startMuted = this.hasAttribute('start-muted') && this.getAttribute('start-muted') !== 'false';

    if (!this.clientInstance && !apiKey && !clientId) {
      this.emitError(new Error('Either client property or api-key and client-id attributes are required'));
      return;
    }

    try {
      this.player = new JaaqVideoPlayer(this.container, {
        videoId: videoId ?? undefined,
        apiKey: apiKey ?? undefined,
        clientId: clientId ?? undefined,
        client: this.clientInstance || undefined,
        baseUrl,
        apiVersion,
        autoplay,
        controls,
        showLogo,
        showTitle,
        showAuthor,
        showDescription,
        showCaptions,
        startMuted,
      });

      this.attachPlayerEvents();
    } catch (error) {
      this.emitError(error instanceof Error ? error : new Error('Failed to initialize player'));
    }
  }

  private attachPlayerEvents() {
    if (!this.player) return;

    this.player.on('loaded', (video) => {
      this.dispatchEvent(
        new CustomEvent('jaaq:loaded', {
          detail: video,
          bubbles: true,
          composed: true,
        }),
      );
    });

    this.player.on('play', () => {
      this.dispatchEvent(
        new CustomEvent('jaaq:play', {
          bubbles: true,
          composed: true,
        }),
      );
    });

    this.player.on('pause', () => {
      this.dispatchEvent(
        new CustomEvent('jaaq:pause', {
          bubbles: true,
          composed: true,
        }),
      );
    });

    this.player.on('timeupdate', (time) => {
      this.dispatchEvent(
        new CustomEvent('jaaq:timeupdate', {
          detail: time,
          bubbles: true,
          composed: true,
        }),
      );
    });

    this.player.on('volumechange', (volume) => {
      this.dispatchEvent(
        new CustomEvent('jaaq:volumechange', {
          detail: volume,
          bubbles: true,
          composed: true,
        }),
      );
    });

    this.player.on('ended', () => {
      this.dispatchEvent(
        new CustomEvent('jaaq:ended', {
          bubbles: true,
          composed: true,
        }),
      );
    });

    this.player.on('error', (error) => {
      this.emitError(error);
    });

    this.player.on('fullscreenchange', (isFullscreen) => {
      this.dispatchEvent(
        new CustomEvent('jaaq:fullscreenchange', {
          detail: isFullscreen,
          bubbles: true,
          composed: true,
        }),
      );
    });
  }

  private emitError(error: Error) {
    this.dispatchEvent(
      new CustomEvent('jaaq:error', {
        detail: error,
        bubbles: true,
        composed: true,
      }),
    );
  }

  private destroyPlayer() {
    if (this.player) {
      this.player.destroy();
      this.player = null;
    }
  }

  /**
   * Gets the current JaaqClient instance
   */
  get client(): JaaqClient | null {
    return this.clientInstance;
  }

  /**
   * Sets a JaaqClient instance for the player to use
   * Reinitializes the player if already connected
   */
  set client(value: JaaqClient | null) {
    this.clientInstance = value;
    if (this.connected) {
      this.destroyPlayer();
      this.initPlayer();
    }
  }

  /**
   * Gets the current video ID
   */
  get videoId(): string | null {
    return this.getAttribute('video-id');
  }

  /**
   * Sets the video ID
   * Updates the video-id attribute and triggers player reinitialization
   */
  set videoId(value: string | null) {
    if (value) {
      this.setAttribute('video-id', value);
    } else {
      this.removeAttribute('video-id');
    }
  }

  /**
   * Starts or resumes video playback
   */
  play(): void {
    this.player?.play();
  }

  /**
   * Pauses video playback
   */
  pause(): void {
    this.player?.pause();
  }

  /**
   * Sets the playback volume
   * @param volume - Volume level between 0 (silent) and 1 (maximum)
   */
  setVolume(volume: number): void {
    this.player?.setVolume(volume);
  }

  /**
   * Toggles audio mute state
   */
  toggleMute(): void {
    this.player?.toggleMute();
  }

  /**
   * Seeks to a specific time in the video
   * @param time - Target time in seconds
   */
  seek(time: number): void {
    this.player?.seek(time);
  }

  /**
   * Returns the current player state
   * @returns Current player state object or null if player not initialized
   */
  getState(): PlayerState | null {
    return this.player?.getState() || null;
  }

  /**
   * Destroys the player instance and cleans up resources
   */
  destroy(): void {
    this.destroyPlayer();
  }
}
